### ISSUE TITLE
No indentation fix on B-Teile

### ISSUE THREAD

**Issue by GeneralGeki** [d120/sitzungsexport#1]
Issue: See title.

Possible fix:
I believe that "fix_indentation" is never called on the content of any Bteil.
My best guess would be to insert a call into the _compile_ function from the _Protocol_ class in models.py

I can write a pull request if someone explains me how I can test it properly

**Comment by miterion** [comment]
Testing the B-Teil output is not easy unfortunately, since those are not shown during the preview. You can, however, amend this quite easily by adding a `print(protocol.bteile)` after the previous print here
https://github.com/d120/sitzungsexport/blob/cc33beab76c29d1b558012849a1110bc4b4c97a4/sitzungsexport/cli.py#L32-L33

Afterwards, you can test this by downloading any pad from the server via the "Export current pad as plain text" option and calling `python cli.py <path to downloaded file>`

**Comment by miterion** [comment]
Fixed in #2
